openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /v1/users:
    get:
      summary: Get all users
      responses:
        "200":
          description: OK
  /users:
    get:
      summary: Get all users (without version)
      responses:
        "200":
          description: OK
